openapi: 3.0.1
info:
  title: The Rick and Morty API
  description: The Rick and Morty API is a REST( API based on the television show Rick and Morty. You will have access to about hundreds of characters, images, locations and episodes. The Rick and Morty API is filled with canonical information as seen on the TV show.
  version: "1"
servers:
  - url: https://rickandmortyapi.com/api
  
paths:
  /character:
    get:
      operationId: getCharacters
      description: Get all Rick and Morty characters
      parameters:
        - name: page
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: integer
          example: 1
          
        - name: name
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
  
        - name: status
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
            enum: [dead, alive, unknown]
            
        - name: species
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
  
        - name: type
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
  
        - name: gender
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
            enum: [female, male, genderless, unknown]
  
      responses:
        "200":
          description: All Rick and Morty characters 

  /character/{characterId}:
    get:
      operationId: getCharacter
      description: Get a Rick and Morty character
      parameters:
        - name: characterId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A single Rick and Morty characters 

  /character/{characterIds}:
    get:
      operationId: getCharactersByIds
      description: Get a Rick and Morty character
      parameters:
        - name: characterIds
          in: path
          required: true
          schema:
            type: array
            items:
              type: integer
          example:
            - 1
            - 2
      responses:
        "200":
          description: Multiple Rick and Morty characters 
          
          

  /location:
    get:
      operationId: getLocations
      description: Get all Rick and Morty locations
      parameters:
      
        - name: page
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: integer
          example: 1
          
        - name: name
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
  
        - name: type
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
  
        - name: dimension
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
  
      responses:
        "200":
          description: All Rick and Morty locations

  /location/{locationId}:
    get:
      operationId: getLocation
      description: Get a Rick and Morty location
      parameters:
        - name: locationId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A single Rick and Morty location

  /location/{locationIds}:
    get:
      operationId: getLocationsByIds
      description: Get multiple Rick and Morty locations
      parameters:
        - name: locationIds
          in: path
          required: true
          schema:
            type: array
            items:
              type: integer
          example:
            - 1
            - 2
      responses:
        "200":
          description: Multiple Rick and Morty characters 
          
          

  /episode:
    get:
      operationId: getEpisodes
      description: Get all Rick and Morty episodes
      parameters:
      
        - name: page
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: integer
          example: 1
          
        - name: name
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
  
        - name: episode
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: integer

  
      responses:
        "200":
          description: All Rick and Morty episodes

  /episode/{episodeId}:
    get:
      operationId: getEpisode
      description: Get a Rick and Morty episode
      parameters:
        - name: episodeId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A single Rick and Morty episode

  /episode/{episodeIds}:
    get:
      operationId: getEpisodesByIds
      description: Get multiple Rick and Morty episodes
      parameters:
        - name: episodeIds
          in: path
          required: true
          schema:
            type: array
            items:
              type: integer
          example:
            - 1
            - 2
      responses:
        "200":
          description: Multiple Rick and Morty characters 